export const act_data = [
    { id: 1, name: "ACT1", sequence_id: [1, 2] },
    { id: 2, name: "ACT2", sequence_id: [3, 4] },
    { id: 3, name: "ACT3", sequence_id: [5, 6] },
    { id: 4, name: "ACT4", sequence_id: [7, 8] },
];

export const sequence_data = [
    { id: 1, name: "Sequence 1", order: 1, items: [1, 2, 3] },
    { id: 2, name: "Sequence 2", order: 2, items: [4, 5, 6] },
    { id: 3, name: "Sequence 3", order: 1, items: [7, 8, 9] },
    { id: 4, name: "Sequence 4", order: 2, items: [10, 11, 12] },
    { id: 5, name: "Sequence 5", order: 1, items: [13, 14, 15] },
    { id: 6, name: "Sequence 6", order: 2, items: [16, 17, 18] },
    { id: 7, name: "Sequence 7", order: 1, items: [19, 20, 21] },
    { id: 8, name: "Sequence 8", order: 2, items: [22, 23, 24] },
];

export const plot_point_data = [
    {
        id: 1,
        name: "Hook",
        header: "",
        order: 1,
        number: 1,
        text: "",
        icon: "",
    },
    {
        id: 2,
        name: "Protogonist",
        header: "",
        order: 2,
        number: 2,
        text: "",
        icon: "",
    },
    {
        id: 3,
        name: "Impetus",
        header: "Landmark 1",
        order: 3,
        number: 3,
        text: "",
        icon: "",
    },
    {
        id: 4,
        name: "stakes",
        header: "",
        order: 1,
        number: 4,
        text: "",
        icon: "",
    },
    {
        id: 5,
        name: "Deliveration",
        header: "",
        order: 2,
        number: 5,
        text: "",
        icon: "",
    },
    {
        id: 6,
        name: "Dramatic Question",
        header: "Landmark 2",
        order: 3,
        number: 6,
        text: "",
        icon: "",
    },
    // ============================ ACT 2
    {
        id: 7,
        name: "New Rules/Allies",
        header: "",
        order: 1,
        number: 7,
        text: "",
        icon: "",
    },
    {
        id: 8,
        name: "Subplot Intro",
        header: "",
        order: 2,
        number: 8,
        text: "",
        icon: "",
    },
    {
        id: 9,
        name: "Trail 1 Win",
        header: "Landmark 3",
        order: 3,
        number: 9,
        text: "",
        icon: "",
    },
    {
        id: 10,
        name: "Trade Off",
        header: "",
        order: 1,
        number: 10,
        text: "",
        icon: "",
    },
    {
        id: 11,
        name: "Cavalier Risk",
        header: "",
        order: 2,
        number: 11,
        text: "",
        icon: "",
    },
    {
        id: 12,
        name: "Midpoint",
        header: "Landmark 4",
        order: 3,
        number: 12,
        text: "",
        icon: "",
    },
    // ============================ ACT 3
    {
        id: 13,
        name: "Subplot return",
        header: "",
        order: 1,
        number: 13,
        text: "",
        icon: "",
    },
    {
        id: 14,
        name: "Desperate measures",
        header: "",
        order: 2,
        number: 14,
        text: "",
        icon: "",
    },
    {
        id: 15,
        name: "Trail 2 Fail",
        header: "Landmark 5",
        order: 3,
        number: 15,
        text: "",
        icon: "",
    },
    {
        id: 16,
        name: "Ramification",
        header: "",
        order: 1,
        number: 16,
        text: "",
        icon: "",
    },
    {
        id: 17,
        name: "Unraveling",
        header: "",
        order: 2,
        number: 17,
        text: "",
        icon: "",
    },
    {
        id: 18,
        name: "Low Point",
        header: "Landmark 6",
        order: 3,
        number: 18,
        text: "",
        icon: "",
    },
    // ============================ ACT 4
    {
        id: 19,
        name: "Epiphany",
        header: "",
        order: 1,
        number: 19,
        text: "",
        icon: "",
    },
    {
        id: 20,
        name: "New Path",
        header: "",
        order: 2,
        number: 20,
        text: "",
        icon: "",
    },
    {
        id: 21,
        name: "Climax",
        header: "Landmark 7",
        order: 3,
        number: 21,
        text: "",
        icon: "",
    },
    {
        id: 22,
        name: "Reconciliation",
        header: "",
        order: 1,
        number: 22,
        text: "",
        icon: "",
    },
    {
        id: 23,
        name: "New Protagonist",
        header: "",
        order: 2,
        number: 23,
        text: "",
        icon: "",
    },
    {
        id: 24,
        name: "New Hook",
        header: "Landmark 8",
        order: 3,
        number: 24,
        text: "",
        icon: "",
    },
];
